/** Valid cedente PJ form (empresa + estrutura) shared by unit tests. */
export const empresaFixture = {
  company: 'Cedente Teste LTDA',
  trade: 'Cedente Teste',
  cnpj: '11222333000181',
  date: '2015-03-10',
  tipoConstituicao: 'ltda',
  financialActivity: 'nao',
  bankruptcy: 'nao',
  judicialReorganization: 'nao',
  businessSector: 'Comércio de insumos',
  cnaeActivity: '4692300',
  economicActivity: 'Comércio atacadista',
  nire: '35200000000',
  exemptStateRegistration: 'nao',
  stateRegistration: '110042490114',
  constitutionCountry: 'Brasil',
  homeCountry: 'Brasil',
  legalNature: 'Sociedade Empresária Limitada',
  shareholderControl: 'Privado nacional',
  email: 'contato@example.com',
  website: '',
  ddi1: '55',
  ddd1: '11',
  telefone1: '40000000',
  irrf: 'tributado',
  fatca: 'nao',
  politicallyExposed: 'nao',
  nonProfit: 'nao',
  bondCompany: 'nao',
  carteiraAdministrada: 'nao',
  possuiUsPersonParticipacao: 'nao',
  fatcaAtividadeFinanceira: 'nao',
  fatcaMaisDe50ReceitaServicos: 'nao',
  fatcaEntidadeSemFinsLucrativos: 'nao',
  fatcaBeneficiarioFinalDeclaracao: 'beneficiarioEfetivo',
  logradouro: 'Alameda Rio Negro',
  numero: '500',
  complemento: 'Sala 1',
  bairro: 'Alphaville',
  cidade: 'Barueri',
  estado: 'SP',
  cep: '06454000',
  pais: 'Brasil',
  tipoEntregaCorrespondencia: 'email',
  correspondenciaEmail: 'contato@example.com',
  patrimonioLiquido: '1000000,00',
  dataBasePatrimonio: '2025-12-31',
  receitaLiquida: '5000000,00',
  periodicidadeBalancete: 'Mensal',
  faturamentoMedioMensal: '400000,00',
  faturamentoUltimoMes: '420000,00',
  possuiParticipacoesSocietarias: 'nao',
  possuiPlanoInvestidor: 'nao',
};

export const estruturaFixture = {
  tipoRepresentante: 'administrador',
  representanteNome: 'Representante Legal',
  representanteEmail: 'representante@example.com',
  representanteCpf: '52998224725',
  representanteRg: '123456789',
  possuiAcionistasSocios: 'sim',
  acionistasSocios: [
    {
      nome: 'Sócio Majoritário',
      cpfCnpj: '52998224725',
      paisConstituicao: 'Brasil',
      capitalVotante: 70,
      capitalTotal: 70,
    },
  ],
  clienteCompanhiaAbertaOuSemFinsLucrativos: 'nao',
  possuiBeneficiariosFinais: 'sim',
  beneficiariosFinais: [
    {
      nome: 'Sócio Majoritário',
      cpfCnpj: '52998224725',
      nacionalidade: 'Brasileira',
      participacaoPercentual: 70,
      outraCidadania: 'nao',
      pepFlag: false,
    },
  ],
  possuiEmpresasColigadas: 'nao',
  possuiEmpresasControladas: 'nao',
  possuiControladoresDiretores: 'nao',
  contasBancarias: [
    {
      tipo: 'corrente',
      banco: '341 - Itaú Unibanco',
      agenciaNumero: '0001',
      agenciaNome: 'Agência Centro',
      contaCorrente: '123456',
      digito: '7',
    },
  ],
  possuiAdministradoresProcuradores: 'sim',
  administradoresProcuradores: [
    {
      tipo: 'administrador',
      nomeRazaoSocial: 'Administrador Adicional',
      email: 'administrador@example.com',
      cpfCnpj: '11144477735',
      docIdentidade: '987654321',
    },
  ],
  possuiResponsaveis: 'nao',
};

export const cedenteFormFixture = { ...empresaFixture, ...estruturaFixture };
