-- AlterTable
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "legal_name" VARCHAR(500);
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "inception_date" DATE;
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "website" VARCHAR(500);
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "registered_address" VARCHAR(500);
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "contact_email" VARCHAR(255);
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "contact_phone" VARCHAR(50);
ALTER TABLE "funds" ADD COLUMN IF NOT EXISTS "extra_info_json" JSONB NOT NULL DEFAULT '{}';
